apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team-alpha
  name: team-alpha-role
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
