apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-alpha
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: team-alpha
      server: 'https://kubernetes.default.svc'
