name: Policy Check

on: [push]

jobs:
  policy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check policies
        run: kyverno apply --dry-run ./platform/policies/kyverno/
